<a href="https://colab.research.google.com/github/Explorer9/miscellaneous/blob/main/Linear_reg_with_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear regression

In [1]:
import torch
import sklearn
from sklearn.model_selection import train_test_split
import torch.nn
import numpy as np

In [48]:
np.random.seed(4)
a=np.random.rand(1000).reshape(-1,1).astype('float32')
b=np.random.rand(1000).reshape(-1,1).astype('float32')

In [51]:
a=np.append(a,b,axis=1)

In [53]:
at=torch.from_numpy(a)
bt=torch.from_numpy(b)
at.shape

torch.Size([1000, 3])

In [54]:
at.requires_grad=True
bt.requires_grad=True

In [55]:
x_train, x_test, y_train, y_test=train_test_split(at,bt,test_size=0.33)

In [56]:
class linearRegression(torch.nn.Module):
    def __init__(self, inputSize, outputSize):
        super(linearRegression, self).__init__()
        self.linear = torch.nn.Linear(inputSize, outputSize)

    def forward(self, x):
        out = self.linear(x)
        return out

In [57]:
inputDim = 3       # takes variable 'x' 
outputDim = 1       # takes variable 'y'
learningRate = 0.01 
epochs = 10000

In [58]:
model=linearRegression(inputDim,outputDim)
criterion = torch.nn.MSELoss() 
optimizer = torch.optim.SGD(model.parameters(), lr=learningRate)

In [59]:

for i in range(epochs):
  
 
  output=model(x_train)
  loss=criterion(y_train,output)
  optimizer.zero_grad()
  loss.backward(retain_graph=True)
  if i%100==0:
    print(loss)
  optimizer.step()




tensor(1.3693, grad_fn=<MseLossBackward>)
tensor(0.0219, grad_fn=<MseLossBackward>)
tensor(0.0127, grad_fn=<MseLossBackward>)
tensor(0.0077, grad_fn=<MseLossBackward>)
tensor(0.0046, grad_fn=<MseLossBackward>)
tensor(0.0028, grad_fn=<MseLossBackward>)
tensor(0.0017, grad_fn=<MseLossBackward>)
tensor(0.0010, grad_fn=<MseLossBackward>)
tensor(0.0006, grad_fn=<MseLossBackward>)
tensor(0.0004, grad_fn=<MseLossBackward>)
tensor(0.0002, grad_fn=<MseLossBackward>)
tensor(0.0001, grad_fn=<MseLossBackward>)
tensor(8.6949e-05, grad_fn=<MseLossBackward>)
tensor(5.4030e-05, grad_fn=<MseLossBackward>)
tensor(3.3862e-05, grad_fn=<MseLossBackward>)
tensor(2.1442e-05, grad_fn=<MseLossBackward>)
tensor(1.3740e-05, grad_fn=<MseLossBackward>)
tensor(8.9267e-06, grad_fn=<MseLossBackward>)
tensor(5.8881e-06, grad_fn=<MseLossBackward>)
tensor(3.9483e-06, grad_fn=<MseLossBackward>)
tensor(2.6932e-06, grad_fn=<MseLossBackward>)
tensor(1.8691e-06, grad_fn=<MseLossBackward>)
tensor(1.3193e-06, grad_fn=<MseLossB

In [60]:
for name, param in model.named_parameters():
  print(name, param.data)

linear.weight tensor([[-1.8259e-07,  8.1540e-02,  9.1846e-01]])
linear.bias tensor([1.2020e-06])


In [61]:
for i in range(len(x_test)):
  print(model(x_test[i]).data,y_test[i])

tensor([0.8808]) tensor([0.8808], grad_fn=<SelectBackward>)
tensor([0.9694]) tensor([0.9694], grad_fn=<SelectBackward>)
tensor([0.0755]) tensor([0.0755], grad_fn=<SelectBackward>)
tensor([0.0890]) tensor([0.0890], grad_fn=<SelectBackward>)
tensor([0.5026]) tensor([0.5026], grad_fn=<SelectBackward>)
tensor([0.4224]) tensor([0.4224], grad_fn=<SelectBackward>)
tensor([0.4051]) tensor([0.4051], grad_fn=<SelectBackward>)
tensor([0.9023]) tensor([0.9023], grad_fn=<SelectBackward>)
tensor([0.1818]) tensor([0.1818], grad_fn=<SelectBackward>)
tensor([0.6113]) tensor([0.6113], grad_fn=<SelectBackward>)
tensor([0.7531]) tensor([0.7531], grad_fn=<SelectBackward>)
tensor([0.7940]) tensor([0.7940], grad_fn=<SelectBackward>)
tensor([0.2842]) tensor([0.2842], grad_fn=<SelectBackward>)
tensor([0.9718]) tensor([0.9718], grad_fn=<SelectBackward>)
tensor([0.8738]) tensor([0.8738], grad_fn=<SelectBackward>)
tensor([0.0866]) tensor([0.0866], grad_fn=<SelectBackward>)
tensor([0.2786]) tensor([0.2786], grad_f